version: 0.2
phases:
 install:
  runtime-version:
    nodejs: 16
  commands:
    - branch=$CODEBUILD_SOURCE_VERSION
    - branch=${branch,,}
    - echo $branch
    - npm install -g python 
    - npm install -g aws-cdk
    - python --version && pip --version
    - pip install aws-cdk.cdk
    - pip install boto3
    - pip install boto
    - pip install pygit2
 build:
  commands:
    - python -m pip install -r requirements.txt
    - cdk deploy -c branch=$branch
